set_property IOSTANDARD LVCMOS33 [get_ports C]
set_property IOSTANDARD LVCMOS33 [get_ports {S[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {X[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {X[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[0]}]
set_property PACKAGE_PIN J2 [get_ports {S[1]}]
set_property PACKAGE_PIN K2 [get_ports {S[0]}]
set_property PACKAGE_PIN P3 [get_ports {X[1]}]
set_property PACKAGE_PIN P2 [get_ports {X[0]}]
set_property PACKAGE_PIN N4 [get_ports {Y[1]}]
set_property PACKAGE_PIN R1 [get_ports {Y[0]}]

set_property PACKAGE_PIN J3 [get_ports C]
